CSR_computation:
  apply_CSR: 1
  compute_CSR: 1
  transverse_on: 1
  workdir: /pscratch/sd/o/ocamacho/w_chicane_pydf_outputs_csron/
  write_beam:
  - 15
  - 138
  - 164
  - 315
  - 323
  - 332
  - 340
  - 491
  - 516
  - 640
  write_name: w_chicane_-20.5_-39.0
  write_wakes: true
  xbins: 16
  xlim: 3
  zbins: 32
  zlim: 3
CSR_integration:
  n_formation_length: 1
  xbins: 100
  zbins: 100
input_beam:
  ParticleGroup_h5: /global/cfs/cdirs/m669/obed/begbc20_beams/BEGBC20_1M_-20.5_-39.0.h5
  style: ParticleGroup
input_lattice:
  lattice_input_file: /global/homes/o/ocamacho/pydfCSR_sims/lattice_files/bc20w_c.yaml
particle_deposition:
  filter_order: 1
  filter_window: 9
  upper_limit: 2000
  velocity_threhold: 1000
  xbins: 300
  xlim: 5
  zbins: 300
  zlim: 5
