input_beam:
  style: ParticleGroup
  ParticleGroup_h5: /global/cfs/cdirs/m669/obed/begbc20_beams/test_beam.h5
  
input_lattice:
  lattice_input_file: lattice_files/b1le_0.yaml

particle_deposition:
  xbins: 300 #300         # number of grids in x for particle deposition
  zbins: 300 #300         # number of grids in y for particle deposition
  xlim:  5           # range in x in the unit of sigma_x
  zlim: 5            # range in z in the unit of sigma_z
  filter_order: 1    # 0 for no filter
  filter_window: 9
  velocity_threhold : 1000
  upper_limit: 2000   # upper limit for interpolation


CSR_integration:
  n_formation_length: 1
  zbins: 100 #200
  xbins: 100 #200


CSR_computation:
  compute_CSR: 1             # if zero, only track the beam
  apply_CSR: 1                 # flag apply CSR to particles
  transverse_on: 1            # flag include transverse wake
  xbins: 16                   # The mesh on which CSR wake is computed
  zbins: 32
  xlim: 3
  zlim: 3
  #Want output at beginning of D15 and end of D18 (top of the W) for training       
  write_beam: [15,    138, 164,   315, 323,    332, 340,    491, 516,  640] # First 50 steps have CSR
  write_wakes: true
  write_name: 'test_beam'
  # This is where we write the sim output to
  workdir: '/pscratch/sd/o/ocamacho/w_chicane_pydf_outputs_csron/'


